### ISSUE TITLE
pointer arithmetic bug

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos#124]
following snipped 
```
#include <stdio.h>

int main() {
  int offs1 = 0x10;
  int offs2 = 0x20;
  printf("ptr: %x\n", (unsigned int)(((char *)0x8000) + offs1 + offs2));
}
```

compiled without optimizations flags with:
```
clang --config /usr/local/llvm-mos-sdk/build/sim.cfg hello.c
```

prints incorrect `ptr: 8000` (with -Os / -O2 it prints correct`ptr:8030`)

**Comment by mrk-its** [comment]
And it seems it is not printf issue, following snipped has identical behavior:
```
#include <stdio.h>

void print_hex(unsigned v) {
    putchar(v < 10 ? '0' + v : 'a' + v - 10);
}

void print_hex2(unsigned v) {
    print_hex((v >> 4) & 0xf);
    print_hex(v & 0xf);
}

void print_hex4(unsigned v) {
    print_hex2(v >> 8);
    print_hex2(v & 0xff);
}

int main() {
  int offs1 = 0x10;
  int offs2 = 0x20;
  unsigned result = (unsigned int)(((char *)0x8000) + offs1 + offs2);
  print_hex4(result);
  putchar('\n');
}
```

**Comment by mysterymath** [comment]
Have this reproduced and narrowed down to the first Combine phase, right before Legalization. It's a surprisingly slippery bug though; I'm going to have to single-step through this tomorrow and see if I can get to the bottom of it.

**Comment by mysterymath** [comment]
Amazingly, this was a GlobalISel bug in upstream! The scenario that triggers it is pretty niche, it only happens when there's chained additions with an integer constant base address, just like the code you posted. It also won't happen unless the whole chain makes it to the backend, which explains the optimization level sensitivity.

I've got a fix; running the regression tests on it now.
