### ISSUE TITLE
Overeager optimizer in C++

### ISSUE THREAD

**Issue by damosan314** [llvm-mos/llvm-mos#184]
The C++ compiler will optimize out the empty while loop.

cout << _S("  ") << (char *)"String = " << a << endl ;

while( true );

return 0;

**Comment by mysterymath** [comment]
I've started a FAQ, since this is something that comes up a lot.

https://llvm-mos.org/wiki/Frequently_asked_questions

The short version is that the above code snippet is undefined behavior in C++; the standard explicitly allows the compiler to consider all loops to terminate. The compiler will do so, and, since the loop body will empty, the loop will be removed.
