### ISSUE TITLE
Enable int24_t and uint24_t

### ISSUE THREAD

**Issue by epi** [llvm-mos/llvm-mos#188]
Some devices such as VBXE (currently a common upgrade to 8-bit Ataris) use 3-byte addresses and it'd be very convenient to have a built-in type rather than hacking a library boilerplate for it.
It'll be also useful as integer representation of 65c816 long pointers.

It's already in stdint.h, guarded by `__INT24_TYPE__`, and has been in avr-gcc for some time.
Matching issue for AVR clang: https://github.com/llvm/llvm-project/issues/53463

**Comment by mysterymath** [comment]
These are non-standard, but it looks like _BitInt and _UnsignedBitInt are scheduled for inclusion in C23. These allow arbitrary precision integers, using functionality that we already needed to implement internally, since clang can emit odd bit widths inside the compiler. These were disabled in LLVM-MOS, but I've just switched them on, so this should be in the next release.

Example:
```
_BitInt(24) plus(_BitInt(24) a, _BitInt(24) b) {
  return a + b;
}
```

```
plus:                                   ; @plus
; %bb.0:                                ; %entry
	clc
	adc	mos8(__rc3)
	tay
	txa
	adc	mos8(__rc4)
	tax
	lda	mos8(__rc2)
	adc	mos8(__rc5)
	sta	mos8(__rc2)
	tya
	rts
```

**Comment by epi** [comment]
Super cool, thank you!
Looks like (at least in C++) `_UnsignedBitInt(n)` is not available, but `unsigned _BitInt(n)` works as expected.
