### ISSUE TITLE
Link-time relaxation of zero-page symbols

### ISSUE THREAD

**Issue by davidgiven** [llvm-mos/llvm-mos#228]
If you're referring to a symbol imported from another object file, there's currently no way to tell the assembler whether it's in zero page or not, which means it has to generate the 16-bit address encoding rather than the 8-bit zero page address encoding when doing the assembly.

cc65 solves this with the `.zpimport` directive, which marks the symbol as being in zero page, but it looks like the preferred way for LLVM would be to rewrite the instructions during the link process if the linker determines that the operand is in zero page.

See https://github.com/llvm-mos/llvm-mos-sdk/pull/80.

**Comment by johnwbyrd** [comment]
https://llvm-mos.org/wiki/Assembler_relaxation

**Comment by mysterymath** [comment]
Ah, I asked David to open this issue. This is to add a linker relaxation mechanism to rewrite absolute instructions to their ZP forms based on the actual computed addresses at link time. If it worked right, I think it would relieve the assembler from needing to know whether or not a given external symbol was in the zero page.

This type of linker optimization appears to be very, very common in LLVM targets; typically only the largest form of a branch or memory operation is emitted, and the linker uses an optimizing relocation to clean up one or more instructions after the fact. I got a good look at this recently when looking at how PLT and GOT entries get cleaned up on various platforms.

**Comment by johnwbyrd** [comment]
I'm not going to say this is impossible... However, if my understanding of what you are trying to do is correct, it would require the linker to have some pretty in-depth knowledge of the instructions that the assembler has emitted, and the design of LLVM tries to keep that info away from the linker.  @mysterymath , could you do me the favor of pointing me at some code you've seen that does this on other platforms?

**Comment by davidgiven** [comment]
Doesn't LTO always require linker knowledge of the instruction set? For example, inlining functions will require adjusting jump addresses, branch offsets, expanding conditional branches to inverse-branch-and-jump, etc.

**Comment by mysterymath** [comment]
LTO actually has two meanings. The older is as you describe; the linker fixing up machine code. The newer is the compiler deferring machine code generation until link time. The linker then produces the actual machine code, with the symbol resolutions becoming an input to the compilation process. The latter meaning has mostly come to supplant the former.

While we do the latter LTO by default, we do none of the former. Unfortunately, the latter LTO can't know the actual numeric values of symbols, since the code hasn't been laid out yet.

I've found some examples in the x86-64 psABI that seem to be something similar to what  we're discussing here; I'll spend some of today looking into how they've implemented it in their linker target.

**Comment by davidgiven** [comment]
Ah. Well, you can tell how long it's been since I touched modern compilers... for this to work the linker must have access to the underlying LLVM bitcode for each object file, so this must be embedded in the object files along with the unoptimised native code? So I don't need to worry about LTO happening on any of my hand-written 6502 code.

**Comment by mysterymath** [comment]
Having the native code and the bitcode together is called "fat LTO", and it's something we're actually working on in my fay job. Right now, at least for llvm, you can either store bitcode or object code, but not both.

Note that all the C you've added to the SDK gets shipped to the user as bitcode; it's only actually compiled to 6502 machine code once linked against the actual user executable. But yeah, assembly code is guaranteed to stay out of the process; in a given link, there's all of the bitcode slurped together into one object file, then there's everything else.

**Comment by mysterymath** [comment]
The X86-64 LLD code for the fixups I was looking at is here: https://github.com/llvm/llvm-project/blob/main/lld/ELF/Arch/X86_64.cpp#L840

There's direct switching on the opcode and monkey-patching of the binary there. It doesn't even look like they have a very principled approach; just if's and direct hex manipulation. They're able to get by with much simpler code than we would end up with though, since they (and other) architectures have more regular encodings than our smorgasbord.

It looks like we'd need to use the RISCV relaxation interface for this to work, though. The linker would need a table from absolute opcodes to ZP opcodes, then it could go to work fixing up ADDR16 relocations.

**Comment by mysterymath** [comment]
From https://www.sifive.com/blog/all-aboard-part-3-linker-relaxation-in-riscv-toolchain, it looks like using RISC-V-style linker relaxation has some additional consequences:
- The linker needs to handle .align directives, since the binary sections change size during the link.
- The linker needs to process debug information during the link, for the same reason.

Getting this all to work right sounds like it was a pretty big project for RISC-V; I didn't realize that they're the only ones that are doing it. It looks like the other link-time optimizations leave code the same size, which would almost defeat the purpose here, since we'd have to insert NOPs.

**Comment by davidgiven** [comment]
That suggests it's not worth it for my specific use case, as (IIRC) compiler-generated code uses explicit annotations for addressing mode sizes and I'm being weird by having hand-written machine code.

Two alternatives I can think of are (a) a directive to mark a particular symbol as being known to come from zero page, so the assembler knows what addressing mode to use, and probably more interestingly (b) emission of assembly from the linker. 6502 programs are small enough that assembling the entire program, with absolute addresses throughout, is entirely possible. The assembler would then know exactly where everything is and can generate code accordingly. But I have no idea whether this is possible in LLVM.

**Comment by mysterymath** [comment]
The former seems like the way to go for hand-written assembly; I've opened #231 for this.

**Comment by davidgiven** [comment]
Thanks.

**Comment by mysterymath** [comment]
Closing as obsolete; #231 is complete, and the `.zeropage` directive is now available.

**Comment by davidgiven** [comment]
(very belated thank-you!)
