### ISSUE TITLE
Write 65xx simulator

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#26]
In order to test generated code easily, we want to simulate CPUs within the 65xx family.

Although LLVM doesn't currently have any facility for enabling the generation of simulators, the more I look at this problem, the more I think that the simplest and most direct way to write one, is to create a novel tablegen backend for it.

This sounds nastier than I think it will actually be.  And, if I'm right, the result will be immediately useful upstream.

Purposely, I don't intend to design a cycle-accurate emulator, for several reasons.  One, no code generated by llvm-mos should be timing sensitive.  Two, we specifically need to be able to simulate code running on _all_ the odd 65xx variants out there.  And we don't have netlists for, say, the 65816 or the Ricoh processors.  Third, supporting additional processors in the simulator would be a small and incremental amount of work.

The simulated target will purposely have a trivial virtual architecture.  Code will be loaded at a fixed address ($0200), and simulator code can thunk to the underlying operating system, by reading and writing a memory range at a fixed location ($FFxx for 6502, $FFFFxx for the 65816.)

If I structure this code correctly, then the tablegen backend should be able to generate both a traditional stepped simulator, as well a qemu-style optimized backend that treats non-branching code as invariant. and thus compiles blocks of 65xx code to extremely fast native code. Not that we care about high-speed simulation specifically for the 65xx, but I think that the LLVM community would care a _lot_ about high-speed CPU simulation in llvm.  Like... a _LOT_.

See also Klaus2k5's code for validating emulators.  https://github.com/Klaus2m5/6502_65C02_functional_tests

**Comment by mysterymath** [comment]
Is this a blocker for end-to-end testing, or can we pull one of the existing simulators/emulators as a dependency first?

It's not exactly correct to say we have no cycle-accurate issues. The compiler will need to avoid generating RMW operations on NMOS 6502s for volatile pointers. Due to the double-write bug on those processors, the compiler may otherwise accidentally trigger an untended hardware operation due to the spurious write.

We can test this fairly well in unit tests for the code generator, but that's true for most of the project, really. End-to-end tests are  bigger, slower, harder to debug, and harder to write than unit, integration, and diff tests. The main advantage they bring is fidelity to the end use case: they catch "unknown unknowns"; stuff we haven't thought of, but that the emulator/simulator authors did.

**Comment by johnwbyrd** [comment]
I'd like to understand the RMW bug you're referring to specifically before I respond.  Pointers please?

**Comment by johnwbyrd** [comment]
In any case, what I do needs to admit the future possibility of different emulation techniques (cycle accuracy, per instruction classic emulation, and qemu style dynamic recompilation) as well as the world of 65xx near clones.  Again, this sounds nastier than I think it will be.  Choice of the right abstractions up front, may make this small work... llvm is already doing like 80% of the heavy lifting involved.

**Comment by mysterymath** [comment]
Looks like I remembered this a bit wrong too; the CMOS version didn't exactly fix it, it now just does double-reads instead of double writes. From the 6502 Wikipedia page:

The 6502 read-modify-write instructions perform one read and two write cycles. First, the unmodified data that was read is written back, and then the modified data is written. This characteristic may cause issues by twice accessing hardware that acts on a write. This anomaly continued through the entire NMOS line, but was fixed in the CMOS derivatives, in which the processor will do two reads and one write cycle. Defensive programming practice will generally avoid this problem by not executing read/modify/write instructions on hardware registers.

**Comment by mysterymath** [comment]
I just remembered that some of the indexed operations will also issue stray reads to totally separate locations; that was a big correctness TODO, since we'd need to make sure again not to use certain indexed operations either for volatile operations.

**Comment by johnwbyrd** [comment]
My current intention is to create a small class library that can be subclassed into an instruction emulator, a cycle exact emulator, JIT, etc. as our requirements grow more demanding.  Additionally, it sounds like we may need to create specific emulator variants for testing volatile features, such as a virtual device that increments a particular address on read, and another on write.  It may also be useful to create an emulator variant that traps on reads or writes to stray locations.  lldb as well has a place to plug in a MOS emulator, when one exists.  If base classes and specializations are chosen reasonably, then the result should be a class of related emulators, instead of "the emulator." A hello world type proof of concept is in order.

**Comment by johnwbyrd** [comment]
The primary use for such an emulator, of course, is part of automated test suites.  Even a quick regression test with imperfect emulation is better than nothing.

**Comment by jackoalan** [comment]
Would the simulator be made to work in conjunction with LIT/FileCheck? So writes to $FFxx simply print a line that can be verified with a CHECK comment?

**Comment by johnwbyrd** [comment]
Yes, I would hope to see something like **llvm-emu --target mos binary-file**, with the output checked in lit.  This would be the emulator's principal use case.

**Comment by johnwbyrd** [comment]
This continues, as I find time to work on it.  I've added support for emulator libraries, in the same style as Disassembler and AsmParser libraries, within cmake, so that other platforms could theoretically leverage this work in the future.

**Comment by ncatelli** [comment]
Hello, I've been doing some work on an emulator framework for my own 6502 tooling and figured I'd drop a line to see if it could be of any use to y'all. 

https://github.com/ncatelli/mainspring/blob/main/examples/microcode_step_capture.rs

**Comment by johnwbyrd** [comment]
> Hello, I've been doing some work on an emulator framework for my own 6502 tooling and figured I'd drop a line to see if it could be of any use to y'all.
> 
> https://github.com/ncatelli/mainspring/blob/main/examples/microcode_step_capture.rs

Hi ncatelli, your work is interesting but it would to my knowledge be the only bit of Rust associated with this project, and the only tool written in Rust that is associated with LLVM in general.  LLVM compiles Rust, but all LLVM tools are written in python or C++.

**Comment by johnwbyrd** [comment]
Perhaps you could help in other ways.  You may wish to review the bug list, pick out a few issues, and try writing a few patches.
