### ISSUE TITLE
Weird side-effect from function call "in the future"

### ISSUE THREAD

**Issue by gergoerdi** [llvm-mos/llvm-mos#266]
I've uploaded full reproducer to https://github.com/gergoerdi/llvm-mos-issue-charset

In particular, its `main` function, defined in C, is:

```
int main ()
{
    uint8_t mem[4 * 1024 - 0x200];
    select_and_load_file(mem);

    make_charset();
    return 0;
}
```

The `make_charset` function is supposed to trash the character set. However, it's only supposed to run *after* `select_and_load_file` returns.  What I'm observing is that `select_and_load_file()` already has the character set garbled, so you don't see any file names. 

If I remove the call to `make_charset`, then the file selector is displayed with normal font.

This bug is quite sensitive to the details of `select_and_load_file`. For example, commenting out parts of its keyboard handling can cause the bug to go away. Hence the large reproducer.

**Comment by mysterymath** [comment]
Hey, thanks for the bug report.

First off, I have a guess, and it's probably a good guess. The implementation of  `make_charset()` doesn't reference the charset through a volatile pointer, so the compiler is free to perform those stores whenever it feels like it. It can inline the whole of `make_charset()` and move it before `select_and_load_file()`. I'm not exactly certain why it would do this, but I think it's at least allowed, so that may be your issue.

Unfortunately, at least as-is, I don't think I'm going to be able to debug this in more detail. I can't build the reproducer with a debug build of the compiler, since trying to mix archictures like this in the bitcode (x86-64 and mos) trips assertions that prevent the compile from proceeding. I hate to say something like "this way of mixing Rust and llvm-mos isn't supported", but I can't effectively support it if I can't run code through a debug build.

You might try using @mrk-its 's https://github.com/mrk-its/rust-mos; it produces IR that's more in-line with what Clang does, so it's much easier to work through things like this. They've also got some nifty libraries bundled for volatile accesses, they've ported most of core, there's some c64 hardware libraries, etc. etc.

**Comment by mysterymath** [comment]
The rust port is only loosely affiliated with llvm-mos; you'd have to ask mrk. IIRC, he maintains a docker image with pre-built.

But, I don't really have the bandwidth or expertise needed to maintain a rust front-end fork, so mrk's codebase is the best supported version that exists to my knowledge. Even then, there's quite a few target support files left stubbed out; inline assembly doesn't work, for instance.

But in any case; mixing x86 and mos bitcode is definitely living in undefined behaviorland, so it comes with all of the nasal demon caveats.
