### ISSUE TITLE
Infinite loop with asm("lda #$02 : sta $19")

### ISSUE THREAD

**Issue by Alcaro** [llvm-mos/llvm-mos#325]
```c
int main() {
    asm volatile("lda #$02 : sta $19");
}
```

->

Killed - processing time exceeded
Program terminated with signal: SIGKILL
Compiler returned: 143

https://godbolt.org/z/zb7jofP5n

This strange syntax is the opcode separator in some 65xx assemblers. Sure, it's a syntax error, but surely crashing the compiler isn't the right way to handle those?

**Comment by mysterymath** [comment]
@johnwbyrd I spent a few moments on this; tracked it down to https://github.com/llvm-mos/llvm-mos/blob/b1fb3d17301ae12619e3a81ce7d5e19c127bed8c/llvm/lib/Target/MOS/AsmParser/MOSAsmParser.cpp#L564

Calling `eatToEndOfStatement` consumes the EndOfStatement virtual token, which causes ParseInstruction while loop from ever terminating: https://github.com/llvm-mos/llvm-mos/blob/b1fb3d17301ae12619e3a81ce7d5e19c127bed8c/llvm/lib/Target/MOS/AsmParser/MOSAsmParser.cpp#L655

Not entirely sure what to do about this though; do you know offhand what should happen here instead?

**Comment by johnwbyrd** [comment]
At a high level, I'm surprised that the higher level of code is percolating the \ and the n down to the assembly parser.  Be that as it may, at a cursory reading it seems to me that the eatThatToken() at

https://github.com/llvm-mos/llvm-mos/blob/b1fb3d17301ae12619e3a81ce7d5e19c127bed8c/llvm/lib/Target/MOS/AsmParser/MOSAsmParser.cpp#L706

should be catching whatever garbage can't be parsed otherwise, and trying to turn it into a token for the TableGen parser to figure out.

I'll try to find time in the next couple days to set up a test case and capture this behavior.  In the meantime, don't do that.  :)

**Comment by mysterymath** [comment]
By the time the eatThatToken is hit, the lexer is already at Eof; it's
already consumed the end of statement token that the loop is looking for. A
quick way to fix this would be to make the loop look for Eof too, but that
seems... inelegant.

**Comment by johnwbyrd** [comment]
Sadly, it seems that that is exactly what AsmParser.cpp expects:

https://github.com/llvm-mos/llvm-mos/blob/c995654bd814344a6b1336aab1cfbb737efd2210/llvm/lib/MC/MCParser/AsmParser.cpp#L1095

Will investigate a little more.
