### ISSUE TITLE
Invalid addressing `stx <absolute>, y` accepted by assembler

### ISSUE THREAD

**Issue by cogwheel** [llvm-mos/llvm-mos#354]
I unwittingly wrote some invalid code of the form:

```asm
stx some_buf, y
```

This is only valid if `some_buf` is on the zeropage. But the symbol was not marked as zeropage in the assembly file.

Here's an [example on compiler explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:7,endLineNumber:10,positionColumn:7,positionLineNumber:10,selectionStartColumn:7,selectionStartLineNumber:10,startColumn:7,startLineNumber:10),source:'extern+char+buf%5B%5D%3B%0A%0Avoid+foo()%3B%0A%0Aasm+(%22%5C%0A.text+%5Cn%5C%0A.globl+foo+%5Cn%5C%0Afoo:+%5Cn%5C%0A++ldy+%231+%5Cn%5C%0A++stx+buf,+y+%5Cn%5C%0A++rts+%5Cn%5C%0A%22)%3B%0A%0Aint+main()+%7B%0A++++foo()%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:mos-nes-mmc3-trunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O3',overrides:!(),selection:(endColumn:12,endLineNumber:10,positionColumn:12,positionLineNumber:10,selectionStartColumn:12,selectionStartLineNumber:10,startColumn:12,startLineNumber:10),source:1),l:'5',n:'0',o:'+llvm-mos+nes-mmc3+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

The resulting machine code for this instruction is `96 00`, aka `stx $00, y`

**Comment by johnwbyrd** [comment]
The assembler relaxation step only kicks in, if a particular instruction has both an 8-bit operand encoding and a 16-bit operand encoding.  I think the assembler is correctly figuring out that only an 8-bit value will do.  For example, if you add buf = 256 to the assembly portion of the code, the assembler complains that it needs a CPU feature that is not currently active.  But since the value of buf is unknown at the time we compile the assembly, we just say "fill in the value of buf here when you know it", and that never happens; so it is left at zero.

I'm a little more concerned that if buf happens to be a 16-bit value, the instruction encoding will silently ignore the top 8 bits, and just render the lower 8 bits into the result.  My recollection is that there's no obvious way, at the point where LLVM-MOS is actually parsing the relocation, to abort the relocation step and say "this parameter is not sane for this type of relocation."  It would be nice if we could stop processing the relocations with a graceful error message, if a particular parameter to a relocation is not sane.

I checked https://www.masswerk.at/6502/6502_instruction_set.html, and I believe $96 is the correct opcode for STX zp,Y , so at least that part is working correctly.

I'm closing this bug as wontfix for now, but if you think this is the wrong choice, please reopen it and we'll think about a long-term solution.

**Comment by cogwheel** [comment]
> I'm a little more concerned that if buf happens to be a 16-bit value, the instruction encoding will silently ignore the top 8 bits, and just render the lower 8 bits into the result.

This is the bug I was trying to report... I just realized I forgot the `, y` when I wrote the resulting assembly code.

> My recollection is that there's no obvious way, at the point where LLVM-MOS is actually parsing the relocation, to abort the relocation step and say "this parameter is not sane for this type of relocation." It would be nice if we could stop processing the relocations with a graceful error message, if a particular parameter to a relocation is not sane.

Am I understanding correctly: 
- the assembler sees the "zeropage" label, and emits `$96, $00` for the machine code.
- The object file also has reference to `some_buf` that will replace the $00 with the actual address at link time.
- The linker places `some_buf` at a 16-bit address
- The value of `some_buf` is silently truncated when being written to the machine code, and that truncation can't be intercepted?

**Comment by johnwbyrd** [comment]
Well, in your example there is no .zeropage section, so there's that.

> The value of some_buf is silently truncated when being written to the machine code, and that truncation can't be intercepted?

It might be more correct to say that I did not see an obvious way of implementing such a check within LLVM.  Here's the relevant code in question, and you're welcome to poke around with it and see if there's a way to warn the user that the relocation value is broken:

https://github.com/llvm-mos/llvm-mos/blob/3a2acdfa8e9b09b4a6d2bfc2bcc17e00ce031413/lld/ELF/Arch/MOS.cpp#L78

**Comment by johnwbyrd** [comment]
Should I reopen this bug?

**Comment by johnwbyrd** [comment]
You know what, since this problem is potentially confusing to sane people, I'll reopen this bug for the moment.
