### ISSUE TITLE
Implement G_ICMP/G_SELECT

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#40]
There's a "not yet implemented" assert that gets hit at https://github.com/llvm-mos/llvm-mos/blob/main/llvm/lib/Target/MOS/MOSInstructionSelector.cpp#L220 under a variety of conditions.

Codegen previous to instruction selection is capable of emitting sequences of the following form:

  %65:any(s1) = G_ICMP intpred(ult), %99:any(s8), %64:any
  %66:any(s1) = G_ICMP intpred(eq), %99:any(s8), %64:any
  %67:any(s1) = G_ICMP intpred(ult), %98:any(s8), %63:any
  %33:any(s1) = G_SELECT %66:any(s1), %67:any, %65:any

LLVM is trying to pipeline these G_ICMP calls for us, and as a result lowering is not only harder, we're doing some work that we are about to throw away.

**Comment by mysterymath** [comment]
This is due to the default legalizer implementations in LegalizerHelper.cpp; LLVM hates branching, for understandable reasons.

Unfortunately, once we get a G_SELECT in the legalizer, it has to carry all the way through to the phase right after instruction selection (finalize isel). The only way to get rid of instructions is control flow, but you can't insert new basic blocks in the instruction selection pipeline. Instead, you have to emit a pseudo to be lowered in the finalize isel phase that "needs custom insertion", which is code for: "might insert a basic block". Most phases naively iterate over the MachineBasicBlocks without accounting for possible changes to the set; this includes Legalizer and InstructionSelect

**Comment by mysterymath** [comment]
There's broadly two ways to deal with this: make the legalizer not emit this, and handle it when it does. It's unclear which is easier for this case; G_ICMP i16, i32, and i64 collectively have a metric ton of cases to handle, but G_SELECT is fairly difficult to lower, since it involves control flow. A good implementation of G_ICMP might also involve control flow, too.

Control flow is trickly to handle in the isel pipeline; pretty much all the passes naively iterate over the basic blocks and assume there are no changes to the set. The one exception I'm aware of is the FinalizeISel pass right after instruction selection, which has dedicated logic to lower pseudos that might introduce or remove basic blocks.

We do get some immediate benefit from the Legalizer handling all of this; it emits terrifically bad code, but it does bring the full set of cases down to 8-bits.

**Comment by mysterymath** [comment]
Yanno, I took a closer look at the code in LegalizerHelper.cpp, and amazingly, this is actually one of the two standard implementations of 16-bit compares on the 6502!

The usual logic is: compare the high byte for equality, then if it's equal, do the comparison on the low byte, otherwise, do the comparison on the high byte. That's exactly what the Legalizer emits: a G_SELECT between the low comparison result and the high comparsion result, based on whether or not the high byte is equal.

Accordingly, if we go ahead and lower G_SELECT to a pseudo-instruction, then emit control flow for it, I think the natural 2-byte comparison sequence sort of just falls out.

**Comment by johnwbyrd** [comment]
An example of lowering G_SELECT to a pseudo, starts around 23:15:

https://www.youtube.com/watch?v=Zh4R40ZyJ2k

**Comment by johnwbyrd** [comment]
See https://github.com/llvm-mos/llvm-mos/tree/bug/issue-40 for a failing G_ICMP/G_SELECT combination.

**Comment by johnwbyrd** [comment]
The game.ll example program in https://github.com/llvm-mos/llvm-mos/tree/bug/issue-40, was actually taken from https://github.com/sgadrat/6502-compilers-bench/blob/master/code_samples/ccgame/game_01_start.c .  So an actual benchmark comparing llvm-mos against other C compilers will be possible after this bug is completed.  I see frequent progress occuring on these issues, thank you.

**Comment by mysterymath** [comment]
This should be more-or-less working; the printf.ll example I'm working off of fails in register allocation now, way down the pipe from instruction selection. You'll have to give the game example another try; chances are something else with it will break, but maybe not.
