### ISSUE TITLE
Review llvm-mos.org

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#49]
The llvm-mos.org web site now has a more substantial body of information in it.  I'd like to modify the projects' READMEs to refer to various pages on llvm-mos.org.

The current contents of the readme have been migrated to https://llvm-mos.org/wiki/Getting_started .  The git readme should be redirect to the appropriate pages on llvm-mos.org.

Additionally, articles on llvm-mos.org should be audited and added as necessary.  The process for adding or modifying content should currently be relatively low friction.

**Comment by mysterymath** [comment]
Sounds Good to Me; I've already gone through most of the codegen-related sections and filled things out a bit. We should probably have a bit of redundancy between the wiki and Github READMEs, just to reduce the number of clicks to get started. But it'd make sense to have the wiki be the source of truth, since there's a lot more structure we can give to the documentation there.

**Comment by johnwbyrd** [comment]
Fixed with ff34023.
