### ISSUE TITLE
Data type narrowing and LSR

### ISSUE THREAD

**Issue by beholdnec** [llvm-mos/llvm-mos#53]
Due to memory and computational constraints inherent to the 6502 architecture, it is important to keep data types as narrow as possible. llvm-mos should be able to detect the maximum range of a variable and narrow it down whenever possible. Currently, if the programmer uses wider types than necessary, it can lead to unnecessary complexity in the output program.

The following code shows this issue:

```c
char gStuff[64];

void foo(char x) {
    for (char i = 0; i < 64; i++) {
        gStuff[i] = i;
    }
}
```

When the program above is compiled in -O2 mode, the output is imperfect but fairly tight:

```
foo:                                    ; @foo
; %bb.0:                                ; %entry
	ldx	#0
LBB0_1:                                 ; %for.body
                                        ; =>This Inner Loop Header: Depth=1
	txa
	sta	gStuff,x
	inx
	cpx	#64
	bne	LBB0_1
; %bb.2:                                ; %for.cond.cleanup
	rts
.Lfunc_end0:
```

However, changing the type of `i` from `char` to `int` results in a drastic increase in complexity:

```
foo:                                    ; @foo
; %bb.0:                                ; %entry
	ldx	#0
	lda	#0
	ldy	#0
	sty	__foo_sstk                      ; 1-byte Folded Spill
LBB0_1:                                 ; %for.body
                                        ; =>This Inner Loop Header: Depth=1
	sta	gStuff,x
	clv
	ldy	__foo_sstk                      ; 1-byte Folded Reload
	sty	mos8(__rc3)
	cpy	#0
	bcs	LBB0_3
; %bb.2:                                ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	bit	__set_v
LBB0_3:                                 ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	sta	mos8(__rc2)
	cmp	#63
	ldy	#0
	bcs	LBB0_5
; %bb.4:                                ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	ldy	#1
LBB0_5:                                 ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	lda	mos8(__rc3)
	cmp	#0
	beq	LBB0_8
; %bb.6:                                ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	ldy	#1
	bvs	LBB0_8
; %bb.7:                                ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	ldy	#0
LBB0_8:                                 ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	lda	mos8(__rc2)
	clc
	adc	#1
	sta	mos8(__rc2)
	lda	mos8(__rc3)
	adc	#0
	sta	__foo_sstk                      ; 1-byte Folded Spill
	lda	mos8(__rc2)
	inx
                                        ; kill: def $ylsb killed $ylsb def $y
	cpy	#0
	bne	LBB0_1
; %bb.9:                                ; %for.cond.cleanup
	rts
```

This occurs despite the program performing the same task. Since the variable `i` is restricted to the range 0 .. 64, the type can be narrowed to an 8-bit integer.

llvm-mos should be able to detect simple cases where a variable can be narrowed, and make it so.

**Comment by mysterymath** [comment]
We do actually do a bit of this already; the "MOSIndexIV" pass looks for 16-bit index variables in loops and lowers them to 8 bits.

If you look really carefully at the assembly in the second version of the code, you can see that that pass is actually working. The X register is carried around the loop completely separately from whatever else is going on there, and the array is actually accessed using the 8-bit ,X addressing mode. It appears (I'm guessing) that the loop's test doesn't receive the same treatment however, which indicates a gap in the cases handled by that pass.

**Comment by beholdnec** [comment]
If the MOSIndexIV pass is designed to narrow index variables in loops, then it takes advantage of some narrowing opportunities but probably misses others. Perhaps it would be good to have a more general data-narrowing pass that takes place earlier in compilation

**Comment by mysterymath** [comment]
We'll probably need both. Loops are a bit special in that there's a circular dependency: both bytes of the 16-bit index are used by the 16-bit increment which becomes used by the next 16-bit increment, and so on. You have to look at the loop as a whole to see that the whole only requires 8 bits. It's a bit like cycle detection in a garbage collector.

In LLVM, this is the SCEV pass, which generates for say, int x in the above loop: (and don't quote me on this): i16:<+, 0, 1>. This encodes that x begins at zero and increases by 1 each time through the loop. IndexIV notes that since the loop edge count is 64, such an IV can fit within 8 bits. We thus turn the index from  (gStuff + i16:<+, 0, 1>) into (gStuff + zero_ext(i8<+, 0, 1>).

There should already be some stuff in LLVM to lower straight-line code, since it'd be important to say, lower 64-bit operations to 32 bits on a 32-bit system. I haven't really gone looking for it yet, though; it may just be a matter of turning it on and/or telling it that we want it to take things down to 8 bits. A lot of this is triggered on the "native" int type, which we did already set to 8 bits, but there may be some optimization that hardcoded i32 (there's a SURPRISING amount of that).

**Comment by mysterymath** [comment]
While optimizing Dhrystone, I enabled Loop Strength Reduction (LSR), even for non-native induction variables (IVs). Loop strengh reduction rewrites all uses of variables that vary with the loop (induction variables) to require maintaining as few as possible, and updating them as cheaply as possible. This will for example convert a multiplication in a loop to an addition of the stride on each iteration, and a host of other optimizations. LSR uses information about target addressing modes to try to produce expressions that will later reduce to addressing modes, rather than computing those values into registers.

A ton of induction variables will be 16-bit or larger on MOS, but that doesn't eliminate the need to rewrite them to e.g. count down to zero. LLVM didn't do this, since LSR wasn't smart enough to avoid production a lot of non-native IVs when smaller IVs would suffice.

Turning this on broke the old IndexIV optimization, since LSR completely rewrites away the narrow IV to a wider one. We need to actually teach LSR how the 6502's addressing modes work. This will require extending its internal interfaces quite a bit; it makes assumptions that are not valid on MOS, so there's no way at present to tell it about MOS addressing modes.

**Comment by beholdnec** [comment]
Here are the latest results as of today.

This program:
```c
char gStuff[64];

void foo(char x) {
    for (int i = 0; i < 64; i++) {
        gStuff[i] = i;
    }
}
```

Gets compiled to:
```
foo:                                    ; @foo
; %bb.0:                                ; %entry
	ldx	#64
	ldy	#0
.LBB0_1:                                ; %for.body
                                        ; =>This Inner Loop Header: Depth=1
	tya
	sta	gStuff,y
	clc
	adc	#1
	tay
	clc
	txa
	adc	#-1
	tax
	lda	#0
	cmp	#0
	bne	.LBB0_1
; %bb.2:                                ; %for.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	txa
	cpx	#0
	bne	.LBB0_1
; %bb.3:                                ; %for.cond.cleanup
	rts
```

**Comment by mysterymath** [comment]
I'm still working on this pretty actively; it's been an absolutely wild ride through LLVM's codebase so far.

I've had to rather substantially alter the date model used by Loop Stength Reduction, which is the primary pass that deals with hardware addressing modes in LLVM. The 6502's addressing modes were completely unrepresentable in that pass, due to the hard assumption that all addressing modes are of the form "base + reg + scale * scalereg", where all of base, reg, and scalereg have exactly the same size.

After attempting about a dozen hacks and alternatives, I've broken that assumption in LoopStrengthReduction; the registers can now be narrower than the full addition, and they're implicitly zero-extended before adding.

This will probably get me in trouble when it comes to upstreaming it, there's no compelling why they should be zero-extended instead of sign-extended, sans for there only being one target that could conceivably care (ours), and that target happening to zero-extend 8-bit indices when they participate in 16-bit addressing modes.

But, ultimately my goal is to write a good compiler for the 6502, and that means teaching LLVM about it's real addressing modes, even if it'll make it more difficult to upstream. We can find a more principled solution with the LLVM guys later.

I've had to disable a number of sections of LSR in the scenario we're dealing with, since I haven't repaired the logic yet, and they were spitting out garbage. I'm still hopeful that once these sections are repaired, LSR should pick really good induction variables to travel around the loop with. At least, it looks fairly promising so far.

Thanks for keeping an eye on this; I'll post an update once I've finished tweaking LSR.

**Comment by mysterymath** [comment]
After quite a lot more futzing with LSR, the given example is now:

```C
char gStuff[64];

void foo(char x) {
    for (int i = 0; i < 64; i++) {
        gStuff[i] = i;
    }
}
```

```
foo:                                    ; @foo
; %bb.0:                                ; %entry
        lda     #0
.LBB0_1:                                ; %for.body
                                        ; =>This Inner Loop Header: Depth=1
        tax
        sta     gStuff,x
        clc
        adc     #1
        cmp     #64
        bne     .LBB0_1
; %bb.2:                                ; %for.cond.cleanup
        rts
.Lfunc_end0:
```

LSR seems to be doing a mostly okay job now from a cursory look at the benchmarks; at the very least, returns are starting to diminish. The changes to it seem fairly brittle; it's clear that we'll need to hammer on LSR a lot more throughout the life of the project, but que sera sera.

Closing this one for now, since there's at least a reasonable pass at handling this kind of optimization, even if it ends up not always "sticking" for one reason or another.
