### ISSUE TITLE
Make integer size configurable

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#60]
On MOS platforms, it is perfectly natural and legal to assume that an int is two bytes.  However, there exists a large body of code that assumes that ints are four bytes or more.

It might be useful to present a command line flag to MOS clang, to convince it to assume that int's are four bytes long.

**Comment by xfix** [comment]
I don't think this should be implemented. 32-bit integers are extremely slow on 6502 and porting the code to work with two byte integers is rather straightforward - replace `unsigned int` with `uint32_t` and `int` with `int32_t`. Additionally, in many cases I suspect that 16-bit `int` is not an issue, for instance if an `int` is used to represent array length then it's fine for it to be 16-bit because 6502 has 16-bit pointers.

**Comment by johnwbyrd** [comment]
"This feature would be slow, therefore it should not exist" is an unconvincing argument to me.  You could make the same argument about targeting the 6502 in general.

**Comment by mysterymath** [comment]
> porting the code to work with two byte integers is rather straightforward - replace unsigned int with uint32_t and int with int32_t

As with most things C, this covers 80% of it, but the rest isn't quite so simple. It's rather common for C devs to encode the "fact" that int is 4 bytes in subtle ways to their data structure layouts; untangling this can require arbitrarily large edits to the algorithms that use them.

Still, we'd need to be careful, since this would define an ABI variant; a 32-bit int function couldn't call a 16-bit int one and vice versa. With the recent calling convention rework, different numbers of imaginary registers all use the same ABI now, so this would be our *only* ABI variant.

**Comment by xfix** [comment]
> It's rather common for C devs to encode the "fact" that int is 4 bytes in subtle ways to their data structure layouts; untangling this can require arbitrarily large edits to the algorithms that use them.

I'm not sure what you mean. If you change `int` to `int32_t` in a structure definition it will be 32-bit. Granted, you may encounter other portability issues, for instance structures that depend on `int`'s alignment being 4, but that's a separate issue.

I tried to think of possible issues with a scheme changing `int` to `int32_t` and `unsigned int` to `uint32_t`, and as far I can tell there are two issues that don't cause outright compilation errors.

First - integer promotions - C language doesn't do arithmetic on `char` or `short` values and casts those to `int` when asked to. I don't think that results of arithmetic calculations being promoted to 16-bit integers instead of 32-bit integers is going to be a big issue for most code however, mostly because of the fact that if there is any `int32_t` value involved then the calculations will be performed using 32-bit math (even when `int` is 16-bit). In most cases I expect integer promotion to only affect constants that overflow (such as `1 << 16`), where Clang will provide a warning.

Another issue is with using standard library functionality (mostly `abs` function as far as I can tell). Clang has `-Wabsolute-value` warning that warns about passing `long` to `abs`, which should warn about passing `int32_t` to `abs` when `int` is 16-bit.

> so this would be our _only_ ABI variant

I suspect it may be necessary to have 16-bit pointers ABI and 24-bit pointers ABI (65816) in the future, but I digress.

**Comment by mysterymath** [comment]
> I'm not sure what you mean. If you change int to int32_t in a structure definition it will be 32-bit. Granted, you may encounter other portability issues, for instance structures that depend on int's alignment being 4, but that's a separate issue.

An example (probably) from LLVM's end-to-end test suite (I'm paraphrasing from memory):
```C
union {
  char bytes[4];
  int x;
}
```

This only depends on the alignment of int being <= 4, but manipulations of this kind will intrinsically break if you change the int size. This kind of thing isn't always so glaring; type punning is rather common in C. See the -fno-strict-aliasing kerfluffle for example.

That being said, if we wanted to go this route, it'd probably be better to fold this together into a "x86 compatibility mode": natural alignments for types, 4-byte int, really anything that C code might implicitly expect. 

Immediately, one trouble with this is that there's no incremental migration path; you'd either be using the "compatibility ABI" or you wouldn't, and it'd really difficult and unsafe to set this up on a function-by-function basis. So, if you wanted to port something from x86 to 6502, the compiler wouldn't really offer any assistance doing so; you'd have to do it all at once, which is the situation without this option.

So if this feature is implemented, the expectation would have to be that some codebases will operate exclusively with this mode enabled, indefinitely. This does have a risk of segmenting the codebases written with the compiler, so we may want be lazy about this and wait until someone has a specific use case in mind.

**Comment by xfix** [comment]
If `int` is consistently replaced with `int32_t` it will look like this.

```c
union {
  char bytes[4];
  int32_t x;
}
```

Everything should still work as expected in this case.

**Comment by mysterymath** [comment]
Ugh, yes, you're right. That's what I get for trying to sneak in comments in between meetings.

**Comment by mysterymath** [comment]
I've been going through our bug backlog, and I spent a bit more time thinking about this one. Given that we generally expect that code will be developed against the SDK (at the very least, writing all your own libcalls will be decidedly uncommon), having a flag like this would change the meaning of any standard library headers that were included, which would break linking against the SDK. If we wanted to work around this, we'd need to use intXX_t types for every parameter in the SDK.

An example of existing prior art for a flag like this is the MSVC compatibility mode in Clang;  this would use the LLP64 64-bit data type model, rather than the UNIX LP64 model. But it's also expected that you compile against either the Windows CRT or MinGW in that case; it would be at least a bit surprising if "int" in your standard library didn't correspond to "int" in your program.

Finally, experience with the SDK has shown that C code written against non-embedded systems tends to assume that integer division, multiplication, and barrel shifts are all single-cycle operations, along with operations like CLZ. It's relatively rare for off-the-shelf C code to perform well on the 6502, and when it does, it's usually smaller libraries that would be easier to fixup by hand.

Accordingly, I'm closing this as wontfix, but I'm open to argumentation to reopen.
