### ISSUE TITLE
Needless spilling of Y register, and a possible solution

### ISSUE THREAD

**Issue by beholdnec** [llvm-mos/llvm-mos#89]
I noticed this problem when experimenting with some test code, which I have uploaded [here](https://gist.github.com/beholdnec/6a7ae8a1b7da73d2367bc3ec427dbfa2)

When compiled with `clang --target=mos -O2 -S test2.cpp`, the generated code includes the following:

```
.LBB0_3:                                ; %select.end
	ldy	#0
	sta	(mos8(__rc0)),y                 ; 1-byte Folded Spill
	ldy	#0
	sty	__save_y
	ldy	#1
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	__save_y
	sta	(mos8(__rc6)),y
	ldy	#1
	sty	__save_y
	ldy	#0
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	__save_y
	sta	(mos8(__rc6)),y
```

Basically, there is a dual use of Y-indirect addressing. A value is loaded with LDA (address),y, then stored with STA (address),y. Because the load and store are so close together, the compiler thinks the Y registers interfere with each other and generates an extraneous spill.

I have written a patch that solves this issue by detecting a spill of Y where Y is defined by LDImm, and simplifies the code. The patch can be found [here](https://github.com/beholdnec/llvm-mos/commit/3788da8f22aff9becfb40c20f375d2e864096691). The patch is somewhat hacky; I am not sure if it is the ideal solution.

With the patch applied, llvm-mos generates the following code:

```
.LBB0_3:                                ; %select.end
	ldy	#0
	sta	(mos8(__rc0)),y                 ; 1-byte Folded Spill
	ldy	#0
	sty	__save_y
	ldy	#1
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	__save_y
	sta	(mos8(__rc6)),y
	ldy	#0
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	#1
	sta	(mos8(__rc6)),y
```

(The initial __save_y is a spill that cannot be repaired by this patch.)

The patch is for discussion, please do not merge it.

(Updated to fix broken code)

**Comment by mysterymath** [comment]
Generally, it's best to fix these things as early in the pipeline as possible; as they say, a stitch in time saves nine.

Here, the saves and reloads are placed by the greedy register allocator, which doesn't know that doing so requires (i.e., clobbers) the Y register. If we made the LDstk and STstk instructions clobber Y as part of their designated effects, then the register allocator would notice the conflict and rematerialize y automatically. It may even be able to save it to another location (say, X, or a zero-page register), avoiding the need to scavenge it.

**Comment by mysterymath** [comment]
I'll help to support you if you're interested in making this change, but this is presently pretty low on my priority list, since I'm operating in "most horrible codegen first" order. 16-bit signed comparisons currently take something like 25 instructions, so this is quite mild by comparison.

**Comment by mysterymath** [comment]
"Yeah, that's bad, but it's not *hilariarously* bad."

**Comment by beholdnec** [comment]
I attempted to specify LDstk and STstk as clobbering Y, but it led to the allocator running out of registers. It seems the solution is not as simple as making LDstk and STstk clobber Y.

**Comment by mysterymath** [comment]
Did you add Y as an implicit def? It seems like the greedy register allocator can't actually handle that; it assumes that loading and storing to stack can't change the live ranges of physical registers (ugh).

Accordingly, I think you'd need to add a YcRegClass virtual register as a real operand; this would create an additional requirement for the register allocator to fulfill.

**Comment by beholdnec** [comment]
I uploaded my work [here](https://github.com/beholdnec/llvm-mos/commit/ebe6478f93569ba848bc71c2520e3d204c84bcb9). I have made LDstk and STstk clobber Y via earlyclobber, but as I said, the allocator runs out of registers. Unless there's something I missed.

**Comment by mysterymath** [comment]
Ah, in that case it might be the other thing... I recall some strangeness
in how the allocator dealt with these very small unspillable live ranges...
I'll see if I can figure it out and unblock the change.

**Comment by mysterymath** [comment]
Took a walk through what the register allocator was doing, step by step.

The broad-strokes problem is that marks the Yc register produced by the LDstks and STstks as unspillable, but also marks the Yc register used by the original STYindir as unspillable. Both of these seem vaguely fine, except that a LDstk gets inserted in between the definition of the STYindir's Yc register and the STYindir itself. Since two unspillable live ranges conflict, it crashes.

If it were to try to rematerialize the STYindir Yc register, it'd be trivially able to do so just by moving it below the LDStk. I'm going to see if I can get the allocator to figure this out.

**Comment by beholdnec** [comment]
I also tried to coax the allocator to rematerialize LDY #immediate rather than spilling, to no avail. LDY clobbers the N and Z registers, making it unsafe to move it around just anywhere in the code.

**Comment by mysterymath** [comment]
Ah, but that's why we maintain the invariant that N and Z cannot be live outside of terminators until ExpandPostRAPseudos. It's extra work, but it allows us to rematerialize things freely, since you can't place something like LDY in a terminator.

**Comment by mysterymath** [comment]
I was able to find a simple way to cause the remat to work in this case, but it doesn't yet pass the general test suite. In this case, there's an easy way to pick between the two "unspillable" live registers: the new one is actually size zero, while the old one *was* size zero, but there's now a spill across it. So we can have the new evict the old.

There's actually a big "Urgent" boolean in line 952 of RegAllocGreedy.cpp for determining whether one unspillable live range can evict another. Adding || (VirtReg.isZeroLength(LIS->getSlotIndexes()) &&
            !Intf->isZeroLength(LIS->getSlotIndexes()))) is the fix; I'll have to see if I can debug the test suite later.

**Comment by mysterymath** [comment]
Actually, I'm going to have to take a rain check on this; I don't think the register allocator is doing a very good job right now in situations like this, even with a fix. I'll leave this open, but I think getting good splitting to ZP registers and rematerialization will be important for optimizing sequences like this, but it'll probably be a chunk of intensive work, and upstream loop optimizations have the chance to remove regions of code like this wholesale, for a similar amount of effort.

Not super happy with doing it in the scavenger, either; since we'd end up ripping it out after moving it further up the pipeline.

**Comment by beholdnec** [comment]
```
.LBB0_3:                                ; %select.end
	ldy	#0
	sta	(mos8(__rc0)),y                 ; 1-byte Folded Spill
	ldy	#1
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	#0
	sta	(mos8(__rc30)),y
	ldy	#0
	lda	(mos8(__rc0)),y                 ; 1-byte Folded Reload
	ldy	#1
	sta	(mos8(__rc30)),y
	cpx	#0
	beq	.LBB0_5
```

It would be nice to avoid redundant ldy #0; In MOSRegisterInfo.cpp we have:
```cpp
  // This needs to occur after the above copy since the source may be Y.
  Register Y =
      Builder.buildInstr(MOS::LDImm, {&MOS::YcRegClass}, {Offset}).getReg(0);

  Builder.buildInstr(IsLoad ? MOS::LDYIndir : MOS::STYIndir)
      .addReg(A, getDefRegState(IsLoad))
      .add(MI->getOperand(3)) // base
      .addUse(Y) // offset
      .addMemOperand(*MI->memoperands_begin());
```

Isn't there an alternative to MOS::LDImm here that LLVM can detect for redundancy?

**Comment by mysterymath** [comment]
This sort of redundancy is better handled late, since prologue epilogue
insertion may also introduce these sorts of loads. Was planning to have
this be part of a peephole pass right before branches are laid out. It's
also definitely not worth spilling or splitting to remove a redundancy.

**Comment by mysterymath** [comment]
But regardless, there's shouldn't even be any spilling here at all. You have essentially a pair of LDimm of two different addresses, based on a branch. The register allocator splits this from needing to be in the A register (for the sta to *__rc30) to being able to be in a GPR, then copied to A, which is excellent. The trouble is then that there aren't actually any GPRs available; A, X, and Y are all busy, so it spills.

What it should have done was split even further: it could copy the GPR to an imaginary register, then to A right before the STA YIndir. There's even a function in the greedy register allocator to do this: RegAllocGreedy.cpp:2110, RAGreedy::tryInstructionSplit. The comment even mentions that it's for exactly this case, "spilling to a wider register".

Trouble is, that doesn't get called because the live range was split around basic blocks, not within a basic block, and this caused the resulting basic blocks to be marked as unsplittable, probably out of paranoia that splitting wouldn't terminate. The game would be to see if we can get the register allocator to call tryInstructionSplit on these (and to make sure tryInstructionSplit actually does what we want) without introducing an infinite loop in the register allocator.

If we can get that working, then there's no spills at all in this case; I'd expect this to improve overall register allocator performance a ton, since we have a zillion zp registers, and spilling to them is incredibly cheap compared to the stack.

**Comment by beholdnec** [comment]
Out of curiosity, I forced local splitting on.
```cpp
  // Local intervals are handled separately.
  if (true || LIS->intervalIsInOneMBB(VirtReg)) {
```
The generated code is quite good (not that this is a safe solution)
```
; %bb.1:                                ; %select.false
	lda	#mos16lo(_ZTV4SubA+4)
	ldx	#mos16hi(_ZTV4SubA+4)
	jmp	.LBB0_3
.LBB0_2:
	lda	#mos16lo(_ZTV4SubB+4)
	ldx	#mos16hi(_ZTV4SubB+4)
.LBB0_3:                                ; %select.end
	ldy	#0
	sta	(mos8(__rc30)),y
	ldy	#1
	txa
	sta	(mos8(__rc30)),y
	lda	mos8(__rc32)
	cmp	#0
	beq	.LBB0_5
```

**Comment by beholdnec** [comment]
Here is my analysis, which should also be taken with a grain of salt.

The reg allocator is able to widen the register classes from Ac to GPR:
```
208B    bb.1:
        ; predecessors: %bb.0
          successors: %bb.3(0x80000000); %bb.3(100.00%)

224B      dead %125:ac = LDImm target-flags(lo) @_ZTV4SubB + 4
232B      %120:gpr = LDImm target-flags(lo) @_ZTV4SubB + 4
240B      dead %119:ac = LDImm target-flags(hi) @_ZTV4SubB + 4
248B      %114:gpr = LDImm target-flags(hi) @_ZTV4SubB + 4
320B      JMP %bb.3

336B    bb.2.select.false:
        ; predecessors: %bb.0
          successors: %bb.3(0x80000000); %bb.3(100.00%)

352B      dead %124:ac = LDImm target-flags(lo) @_ZTV4SubA + 4
360B      %120:gpr = LDImm target-flags(lo) @_ZTV4SubA + 4
368B      dead %118:ac = LDImm target-flags(hi) @_ZTV4SubA + 4
376B      %114:gpr = LDImm target-flags(hi) @_ZTV4SubA + 4

448B    bb.3.select.end:
        ; predecessors: %bb.2, %bb.1
          successors: %bb.4(0x30000000), %bb.5(0x50000000); %bb.4(37.50%), %bb.5(62.50%)

504B      %113:yc = LDImm 0
508B      %123:ac = COPY %120:gpr
512B      STYIndir %123:ac, %4:imag16, %113:yc :: (store 1 into %ir.0, !tbaa !2)
528B      %106:yc = LDImm 1
540B      %117:ac = COPY %114:gpr
544B      STYIndir %117:ac, %4:imag16, %106:yc :: (store 1 into %ir.0 + 1, !tbaa !2)
```

This is good. But there are no more GPR's available. Ideally it should widen the register class to Anyi8 (= GPR + Imag8), and only if no Anyi8's are available should it spill to the stack.

tryInstructionSplit calls SplitEditor::finish, which calls LiveRangeEdit::calculateRegClassAndHint, which calls MachineRegisterInfo::recomputeRegClass. This function attempts to raise the register class to the highest possible given the constraints, i.e. given the reg-classes required by the instructions that use it.

THIS is where the problem lies: LDImm can only load to a GPR, so the reg class remains stuck on GPR. I believe the solution will involve inserting a "[Anyi8] = COPY [GPR]" after LDimm.

**Comment by beholdnec** [comment]
Why doesn't it generate a "Anyi8 = COPY GPR" after LDImm automatically? I believe the reason is, it decides to reMaterialize LDImm instead of copying to an Imag8, falsely believing it will be cheaper to do so.

**Comment by mysterymath** [comment]
Ah, I like the widen stage you've added a lot; pretty clean.

I think it now feels like this solution *should* work, even if it doesn't actually work, for the reasons you gave. I'll take a look at this later tonight/tomorrow; there may be some slight edits to the way tryInstructionSplit or the SplitKit goes about its business that'll make the difference (hopefully without too much negative impact on the other targets.)

**Comment by beholdnec** [comment]
RS_Widen is an experiment, I'm hoping it won't be necessary if we find a simpler solution. If we need to keep it, I'm thinking of renaming it to something like RS_LiteSpill.

**Comment by beholdnec** [comment]
The ldstk-clobber-y branch is probably ok to merge at this point. It passes all the LLVM tests.

**Comment by beholdnec** [comment]
I added a light-spill test. Causing a light-spill is a bit tricky. The conditions under which a light-spill occur are:
1) All GPR's are depleted
2) Global splitting has failed
2) The variable can be copied to an Imag8
3) The spill occurs across basic blocks
